AWSTemplateFormatVersion: "2010-09-09"
Description: Nat Gateway for private subnet
Resources:
  NatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: eipalloc-029f8b7b35b446504
      SubnetId: subnet-0987879b4bce79cd8