AWSTemplateFormatVersion: "2010-09-09"
Description: Nat Gateway for private subnet
Parameters:
  VPCStackName:
    Type: String
    Default: Test-VPC
    Description: The name of the stack that created the VPC
Resources:
  GatewayEIP:
    Type: AWS::EC2::EIP
  NatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId:
        Fn::GetAtt:
          - GatewayEIP
          - AllocationId
      SubnetId:
        Fn::ImportValue: 
          !Sub "${VPCStackName}-Private-Subnet"
      Tags:
        - Key: Name
          Value:
            Fn::Join:
              - ""
              - - Fn::ImportValue: !Sub "${VPCStackName}-VPCID"
                - "-NAT"