AWSTemplateFormatVersion: "2010-09-09"
Description: Nat Gateway for private subnet
Parameters:
  CIDRBlockParameter:
    Type: String
    Default: 10.0.0.0/16
    Description: CIDR Block for the VPC
  VPCName:
    Type: String
    Default: Test-VPC
    Description: Name of the VPC
  PublicSubnetCIDR:
    Type: String
    Default: 10.0.0.0/24
  PrivateSubnetCIDR:
    Type: String
    Default: 10.0.1.0/24
Resources:
  TestVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 
        Ref: CIDRBlockParameter
      Tags:
        - Key: Name
          Value: 
            Ref: VPCName
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: 
        Ref: TestVpc
      CidrBlock:
        Ref: PublicSubnetCIDR
      AvailabilityZone: "us-west-2a"
      Tags:
        - Key: Name
          Value: !Join
                    - ''
                    - - !Ref VPCName
                      - '-Public-Subnet'
  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: TestVpc
      CidrBlock:
        Ref: PrivateSubnetCIDR
      AvailabilityZone: "us-west-2a"
      Tags:
        - Key: Name
          Value: !Join
                    - ''
                    - - !Ref VPCName
                      - '-Private-Subnet'
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Join
                    - ''
                    - - !Ref VPCName
                      - '-InternetGateway'
  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: 
        Ref: InternetGateway
      VpcId: 
        Ref: TestVpc
  PublicSubnetRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: TestVpc
      Tags:
        - Key: Name
          Value: !Join
                    - ''
                    - - !Ref VPCName
                      - '-Public-Route-Table'
  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: PublicSubnet
      RouteTableId:
        Ref: PublicSubnetRouteTable
  PublicSubnetIGRoute:
    Type: AWS::EC2::Route
    DependsOn: InternetGateway
    Properties:
      RouteTableId:
        Ref: PublicSubnetRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: InternetGateway
  PrivateSubnetRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: TestVpc
      Tags:
        - Key: Name
          Value: !Join
                    - ''
                    - - !Ref VPCName
                      - '-Private-Route-Table'
  PrivateSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: PrivateSubnet
      RouteTableId:
        Ref: PrivateSubnetRouteTable
Outputs:
  StackVPC:
    Description: The created VPC ID
    Value: !Ref TestVpc
    Export:
      Name: !Sub "${AWS::StackName}-VPCID"
  PublicSubnetId:
    Description: The public subnet ID
    Value: !Ref PublicSubnet
    Export:
      Name: !Sub "${AWS::StackName}-Public-Subnet"
  PrivateSubnetId:
    Description: The private subnet ID
    Value: !Ref PrivateSubnet
    Export:
      Name: !Sub "${AWS::StackName}-Private-Subnet"