AWSTemplateFormatVersion: "2010-09-09"
Description: Nat Gateway for private subnet
Parameters:
  CIDRBlockParameter:
    Type: String
    Default: 10.0.0.0/16
    Description: CIDR Block for the VPC
  VPCName:
    Type: String
    Default: Test-VPC
    Description: Name of the VPC
  PublicSubnetCIDR:
    Type: String
    Default: 10.0.0.0/24
Resources:
  TestVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 
        Ref: CIDRBlockParameter
      Tags:
        - Key: Name
          Value: 
            Ref: VPCName
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: 
        Ref: TestVpc
      CidrBlock:
        Ref: PublicSubnetCIDR
      AvailabilityZone: "us-west-2a"
      Tags:
        - Key: Name
          Value: !Join
                    - ''
                    - - !Ref VPCName
                      - '-Public-Subnet'
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Join
                    - ''
                    - - !Ref VPCName
                      - '-InternetGateway'
  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: 
        Ref: InternetGateway
      VpcId: 
        Ref: TestVpc